### ISSUE TITLE
Install submodules\diff-gaussian-rasterization failed

### ISSUE THREAD

**Issue by amberhappy** [graphdeco-inria/gaussian-splatting#572]
Problems occur when installing submodules. Windows11, cuda version:11.8, python 3.7, torch: 1.13.1

Processing d:\work\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running bdist_wheel
      running build
      running build_py
      running build_ext
      D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl.exe: 'cp1' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\work\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
          return Version(version)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
Installing collected packages: diff-gaussian-rasterization
  Running setup.py install for diff-gaussian-rasterization ... error
  error: subprocess-exited-with-error

  × Running setup.py install for diff-gaussian-rasterization did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running install
      D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      running build_ext
      D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl.exe: 'cp1' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\work\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
          return Version(version)
        File "D:\SoftWare\anaconda3\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> diff-gaussian-rasterization

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by maxolib** [comment]
Maybe this can help https://github.com/graphdeco-inria/gaussian-splatting/issues/535

**Comment by lt-wang** [comment]
I have the same problem, did you solve it now?

**Comment by ertz10** [comment]
Had the same problem, tried everything. Decided to setup the environment by myself. This should work (Win10, VS2019, CUDA 11.8):

`conda create -n gaussian_splatting python=3.9`
`conda activate gaussian_splatting`
`pip install cudatoolkit=11.8`
`pip install plyfile=0.8.1`
`pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118`
`pip install tqdm`
`pip install submodules/diff-gaussian-rasterization`
`pip install submodules/simple-knn`

Don't forget to set VS typical env variables: 
$INCLUDE="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\<version>\include"
$INCLUDE="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\<version>\lib}x64"
$PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\<version>\bin\Hostx64\x64"

**Comment by liulsg** [comment]
@ertz10  I've tested it. It's totally doable. python=3.11 torch=2.2.0 cuda=12.1

**Comment by saba99** [comment]
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

Processing ./diff-gaussian-rasterization
Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Building wheel for diff-gaussian-rasterization (setup.py) ... error
ERROR: Failed building wheel for diff-gaussian-rasterization
Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

**Comment by pxy522** [comment]
@saba99 hi, have u solve this? thk, i meet the same issue

**Comment by jingyangcarl** [comment]
I had a successful installation with the following

```
conda create -n gs3 python=3.10
conda activate gs3
conda install pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytorch-cuda=12.1 -c pytorch -c nvidia
# verify pytorch installation
pip install plyfile tqdm
pip install submodules/diff-gaussian-rasterization
pip install submodules/simple-knn
```

**Comment by heeeyk** [comment]
> Had the same problem, tried everything. Decided to setup the environment by myself. This should work (Win10, VS2019, CUDA 11.8):
> 
> `conda create -n gaussian_splatting python=3.9` `conda activate gaussian_splatting` `conda install cudatoolkit=11.8` `pip install plyfile=0.8.1` `pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118` `pip install tqdm` `pip install submodules/diff-gaussian-rasterization` `pip install submodules/simple-knn`
> 
> Don't forget to set VS typical env variables: $INCLUDE="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC<version>\include" $LIB="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC<version>\lib}x64" $PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC<version>\bin\Hostx64\x64"
 When i run the code  `pip install submodules/diff-gaussian-rasterization`, it return `ImportError: cannot import name 'packaging' from 'pkg_resources'`.  But i found it can solve by run `python -m pip install setuptools==69.5.1`, then I had a successful installation.  Thanks for you shared!

**Comment by artofcoding-by-hanif** [comment]
Worked with conda python=3.9, cuda 12.4, VS 2022(17.12.0)

conda install cudatoolkit=11.8 
pip install plyfile==0.8.1
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
pip install tqdm
pip install submodules/diff-gaussian-rasterization
pip install submodules/simple-knn 
pip install opencv-python

**Comment by domi-fresh** [comment]
@artofcoding-by-hanif thanks a lot, worked for me - although i do have cuda 12.6 and vs 2019 installed

**Comment by yoimisan** [comment]
For linux user, in my experience, the error is because `torch.version.cuda` return **empty** (usually it will return something like '11.6').

You can verify this by running in terminal:
```bash
python -c "import torch; print(torch.version.cuda)"
```

The solution is to make sure the pytorch is install with cudatoolkit. 

For my experience, maybe a reinstall can solve this. The following is what i do in my ubuntu server (22.04.1)

```bash
# Becuse i do not install official cuda toolkit which contents some compiler that `conda install toolkit=11.6` do not provided
conda install cuda -c nvidia/label/cuda-11.8.0 

conda install cudatoolkit=11.6 plyfile python=3.7.13 pip=22.3.1 pytorch=1.12.1 torchaudio=0.12.1 torchvision=0.13.1 tqdm

pip install submodules/diff-gaussian-rasterization
pip install submodules/simple-knn
pip install submodules/fused-ssim
pip install opencv-python joblib
```

**Comment by StevenHong** [comment]
Hello, I'm having the same issue with this line.
```
match = self._regex.search(version)
TypeError: expected string or bytes-like object
```
The way I fixed it is using the following combo
- python=3.10
- cudatoolkit=11.6
- pip=22.3.1
- pytorch=1.12.1
- torchaudio=0.12.1
- torchvision=0.13.1

I think the key is python3.10 version. I tried python3.7.13 and python3.9 but it gave me error.

My machine: Linux Ubuntu 22.04 with cuda 11.8 installed in /usr/local/cuda-11.8
